spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/load_proj_db
    username: postgres
    password: postgres
  mvc:
    hiddenmethod:
      filter:
        enabled: true
